# _config.yml

title: "My Simple Website"
description: "A simple website with a Word document download link."
baseurl: ""  # Leave empty unless using a subdirectory
url: "https://dmagnet202.github.io"  # Replace with your GitHub Pages URL
theme: minima  # Use the Minima theme or any basic theme

# Use Kramdown as the Markdown processor
markdown: kramdown

# Exclude unnecessary files and directories from being processed by Jekyll
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - assets/css/style.scss  # If this file doesn't exist or shouldn't be processed
  - .nojekyll

# Directory configurations
source: ./
destination: ./_site
